ChessTD2/Models/Tournament.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ChessTD2.Models
{
    public class Tournament
    {
        public int TournamentID { get; set; }
        public string Name { get; set; }

        //public virtual ICollection<Player> Players { get; set; }
        public virtual ICollection<Section> Sections { get; set; }
    }
}

ChessTD2/Controllers/SectionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ChessTD2.DAL;
using ChessTD2.Models;

namespace ChessTD2.Controllers
{
    public class SectionController : Controller
    {
        private TDContext db = new TDContext();
        

        public ActionResult SectionList(int id)
        {
            return View(db.Tournaments.Where(t => t.TournamentID == id).First());
        }

        // GET: Section/Details/5
        public ActionResult Details(int? sId, int? tId)
        {
            if (sId == null || tId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Section section = db.Tournaments.Find(tId).Sections.Where(s => s.SectionID == sId).First();

            if (section == null)
            {
                return HttpNotFound();
            }
            return View(section);
        }

        // GET: Section/Create
        public ActionResult Create(int tId)
        {
            Section section = new Section();
            section.Tournament = db.Tournaments.Find(tId);
            return View(section);
        }

        // POST: Section/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SectionID,Name")] Section section, int tID)
        {
            if (ModelState.IsValid)
            {
                section.Tournament = db.Tournaments.Where(t => t.TournamentID == tID).First();
                db.Tournaments.Where(t => t.TournamentID == tID).First().Sections.Add(section);
                db.SaveChanges();
                return RedirectToAction("SectionList", new { id = tID });
            }

            return View(section);
        }

        // GET: Section/Edit/5
        public ActionResult Edit(int? sId, int? tId)
        {
            if (sId == null || tId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Section section = db.Tournaments.Find(tId).Sections.Where(s => s.SectionID == sId).First();

            if (section == null)
            {
                return HttpNotFound();
            }
            return View(section);
        }

        // POST: Section/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SectionID,Name,Tournament")] Section section)
        {

            if (ModelState.IsValid)
            {
                db.Entry(section).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("SectionList", new { id = section.Tournament.TournamentID });
            }
            return View(section);
        }

        // GET: Section/Delete/5
        public ActionResult Delete(int? sId, int? tId)
        {
            if (sId == null || tId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Section section = db.Tournaments.Find(tId).Sections.Where(s => s.SectionID == sId).First();

            if (section == null)
            {
                return HttpNotFound();
            }
            return View(section);
        }

        // POST: Section/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed([Bind(Include = "SectionID,Tournament")] Section section)
        {
            //Section section = db.Sections.Find(sId);
            db.Sections.Remove(db.Sections.Where(s=>s.SectionID == section.SectionID).First());
            db.SaveChanges();
            return RedirectToAction("SectionList", new { id = section.Tournament.TournamentID });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }  
}

ChessTD2/Controllers/SectionPlayersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ChessTD2.DAL;
using ChessTD2.Models;

namespace ChessTD2.Controllers
{
    public class ParticipantsViewModel
    {
        public ICollection<Player> Participants { get; set; }
        public ICollection<Player> NonParticipants { get; set; }
        public int TournamentID { get; set; }
        public int SectionID { get; set; }
    }
    public class SectionPlayersController : Controller
    {
        private TDContext db = new TDContext();

        public ActionResult Participants(int sId, int tId)
        {
            var vm = new ParticipantsViewModel();
            vm.SectionID = sId;
            vm.TournamentID = tId;
            vm.Participants = db.Tournaments.Where(t => t.TournamentID == tId).First().Sections.Where(s=>s.SectionID== sId).First().Players.OrderBy(p=>p.LastName).ToList();

            var participantIds = vm.Participants.Select(p => p.PlayerID).ToArray();
            vm.NonParticipants = db.Players.Where(np => !participantIds.Contains(np.PlayerID)).OrderBy(np=>np.LastName).ToList();

            return View(vm);
        }

        // POST: SectionPlayers/Add
        //[HttpPost, ActionName("Add")]
        //[ValidateAntiForgeryToken]
        public ActionResult Add(int tId, int sId, int playerID)
        {
            var section = db.Tournaments.Where(t => t.TournamentID == tId).First().Sections.Where(s => s.SectionID == sId).First();
            var player = db.Players.Where(p => p.PlayerID == playerID).First();
            section.Players.Add(player);
            player.Sections.Add(section);
            db.SaveChanges();
            return RedirectToAction(nameof(SectionPlayersController.Participants), new { sId = sId, tId = tId });
        }


        // GET: TournamentPlayers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Player player = db.Players.Find(id);
            if (player == null)
            {
                return HttpNotFound();
            }
            return View(player);
        }

        
        public ActionResult Remove(int tId, int sId, int playerID)
        {
            var player = db.Players.Find(playerID);
            //db.Tournaments.Include(p=>p.Players).Where(t => t.TournamentID == tournamentID).First().Players.Remove(player);
            var section = db.Tournaments.Where(t => t.TournamentID == tId).First().Sections.Where(s => s.SectionID == sId).First();
            section.Players.Remove(player);
            player.Sections.Remove(section);
            db.SaveChanges();
            return RedirectToAction(nameof(SectionPlayersController.Participants), new { sId = sId, tId = tId });
        }
        
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ChessTD2/Controllers/TournamentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ChessTD2.DAL;
using ChessTD2.Models;

namespace ChessTD2.Controllers
{
    public class TournamentController : Controller
    {
        private TDContext db = new TDContext();

        // GET: Tournament
        public ActionResult Index()
        {
            return View(db.Tournaments.ToList());
        }

        // GET: Tournament/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tournament tournament = db.Tournaments.Find(id);
            if (tournament == null)
            {
                return HttpNotFound();
            }
            return View(tournament);
        }

        // GET: Tournament/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tournament/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TournamentID,Name")] Tournament tournament)
        {
            if (ModelState.IsValid)
            {
                db.Tournaments.Add(tournament);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tournament);
        }

        // GET: Tournament/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tournament tournament = db.Tournaments.Find(id);
            if (tournament == null)
            {
                return HttpNotFound();
            }
            return View(tournament);
        }

        // POST: Tournament/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TournamentID,Name")] Tournament tournament)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tournament).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tournament);
        }

        // GET: Tournament/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tournament tournament = db.Tournaments.Find(id);
            if (tournament == null)
            {
                return HttpNotFound();
            }
            return View(tournament);
        }

        // POST: Tournament/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tournament tournament = db.Tournaments.Find(id);
            foreach(Section s in db.Sections.Where(s => s.Tournament.TournamentID == tournament.TournamentID))
            {
                db.Sections.Remove(s);
            }
            db.Tournaments.Remove(tournament);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ChessTD2/Views/Tournament/Create.cshtml
@model ChessTD2.Models.Tournament

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tournament</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ChessTD2/Views/Tournament/Delete.cshtml
@model ChessTD2.Models.Tournament

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tournament</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ChessTD2/Views/Tournament/Details.cshtml
@model ChessTD2.Models.Tournament

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Tournament</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dt>
            Players
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dd>
            @for (int i = 0; i < Model.Sections.Count(); i++)
            {
                @Html.DisplayFor(model => model.Sections.ElementAt(i).Players)
            }

        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TournamentID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ChessTD2/Views/Tournament/Edit.cshtml
@model ChessTD2.Models.Tournament

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tournament</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TournamentID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ChessTD2/Views/Tournament/Index.cshtml
@model IEnumerable<ChessTD2.Models.Tournament>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.TournamentID }) |
            @Html.ActionLink("Details", "Details", new { id=item.TournamentID }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.TournamentID }) |
            @*@Html.ActionLink("Manage Players", "Participants", "SectionPlayers", new { tId = item.TournamentID, sId = item.Sections.First().SectionID }, null) |*@
            @Html.ActionLink("Manage Sections", "SectionList", "Section", new { id = item.TournamentID}, null)
        </td>
    </tr>
}

</table>